import { User, UserRole } from './types';
import { JobResponse, JobType, JobStatus } from './apis/api_job';
import { WorkSessionResponse } from './apis/api_work_session';

// --- MOCK USERS ---
export const mockUsers: User[] = [
  // --- WORKERS (IDs 101+) ---
  {
    id: '101',
    name: 'Nguyễn Văn An',
    email: 'an.nguyen@example.com',
    role: UserRole.WORKER,
    avatar: 'https://i.pravatar.cc/150?img=12',
    verified: true,
    rating: 4.8,
    ratingCount: 24,
    skills: ['React', 'Node.js', 'TypeScript', 'UI/UX Design'],
    bio: 'Full-stack Developer với 3 năm kinh nghiệm\nChuyên về React, Node.js và các công nghệ web hiện đại',
    title: 'Full-stack Developer',
    isPremium: true,
  },
  {
    id: '102',
    name: 'Trần Thị Bình',
    email: 'binh.tran@example.com',
    role: UserRole.WORKER,
    avatar: 'https://i.pravatar.cc/150?img=5',
    verified: true,
    rating: 4.6,
    ratingCount: 18,
    skills: ['Graphic Design', 'Adobe Photoshop', 'Illustrator', 'Figma'],
    bio: 'Graphic Designer sáng tạo\nĐam mê thiết kế và nghệ thuật số',
    title: 'Graphic Designer',
    isPremium: false,
  },
  {
    id: '104',
    name: 'Lê Minh Châu',
    email: 'chau.le@example.com',
    role: UserRole.WORKER,
    avatar: 'https://i.pravatar.cc/150?img=8',
    verified: false,
    rating: 4.2,
    ratingCount: 7,
    skills: ['Content Writing', 'SEO', 'Marketing'],
    bio: 'Content Writer & SEO Specialist\nGiúp doanh nghiệp tăng trưởng thông qua nội dung chất lượng',
    title: 'Content Writer',
    isPremium: false,
  },
  {
    id: '106',
    name: 'Phạm Quốc Duy',
    email: 'duy.pham@example.com',
    role: UserRole.WORKER,
    avatar: 'https://i.pravatar.cc/150?img=15',
    verified: true,
    rating: 4.9,
    ratingCount: 56,
    skills: ['Python', 'Machine Learning', 'Data Science', 'AI'],
    bio: 'AI/ML Engineer\nChuyên gia về trí tuệ nhân tạo và học máy',
    title: 'AI/ML Engineer',
    isPremium: true,
  },
  {
    id: 'worker1',
    name: 'Trần Văn A',
    fullName: 'Trần Văn A',
    email: 'worker1@example.com',
    role: UserRole.WORKER,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=A',
    verified: true,
    rating: 4.8,
    ratingCount: 15,
    skills: ['Sửa chữa điện', 'Lắp đặt ống nước', 'Bảo trì'],
    bio: 'Thợ điện nước tay nghề cao. Hơn 5 năm kinh nghiệm làm việc tại các công trình dân dụng.',
    title: 'Thợ điện dân dụng',
    isPremium: false,
  },
  {
    id: 'worker2',
    name: 'Lê Thị B',
    fullName: 'Lê Thị B',
    email: 'worker2@example.com',
    role: UserRole.WORKER,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=B',
    verified: true,
    rating: 4.9,
    ratingCount: 42,
    skills: ['Photoshop', 'Illustrator', 'Logo Design'],
    bio: 'Thiết kế đồ họa Freelance. Chuyên thiết kế bộ nhận diện thương hiệu cho các startup.',
    title: 'Thiết kế đồ họa',
    isPremium: false,
  },
  {
    id: 'worker3',
    name: 'Phạm Minh C',
    fullName: 'Phạm Minh C',
    email: 'worker3@example.com',
    role: UserRole.WORKER,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=C',
    verified: false,
    rating: 4.5,
    ratingCount: 8,
    skills: ['Dạy kèm', 'Toán học', 'Vật lý'],
    bio: 'Gia sư Toán Lý lớp 10-12. Sinh viên năm cuối ĐH Bách Khoa. Kinh nghiệm ôn thi điểm cao.',
    title: 'Gia sư Toán Lý',
    isPremium: false,
  },
  {
    id: 'worker4',
    name: 'Nguyễn Thu D',
    fullName: 'Nguyễn Thu D',
    email: 'worker4@example.com',
    role: UserRole.WORKER,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=D',
    verified: true,
    rating: 4.7,
    ratingCount: 25,
    skills: ['SEO', 'Content Marketing', 'Copywriting'],
    bio: 'Content Writer SEO. Viết bài chuẩn SEO, tăng traffic tự nhiên cho website.',
    title: 'Content Writer SEO',
    isPremium: false,
  },
  {
    id: 'worker5',
    name: 'Hoàng Văn E',
    fullName: 'Hoàng Văn E',
    email: 'worker5@example.com',
    role: UserRole.WORKER,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=E',
    verified: true,
    rating: 4.6,
    ratingCount: 12,
    skills: ['ReactJS', 'TypeScript', 'Tailwind'],
    bio: 'Lập trình viên ReactJS. 3 năm kinh nghiệm frontend, chuyên làm dashboard.',
    title: 'Lập trình viên ReactJS',
    isPremium: false,
  },
  {
    id: 'worker6',
    name: 'Vũ Thị F',
    fullName: 'Vũ Thị F',
    email: 'worker6@example.com',
    role: UserRole.WORKER,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=F',
    verified: false,
    rating: 4.4,
    ratingCount: 19,
    skills: ['Excel', 'MISA', 'Báo cáo thuế'],
    bio: 'Kế toán tổng hợp. Cẩn thận, tỉ mỉ, có chứng chỉ kế toán trưởng.',
    title: 'Kế toán tổng hợp',
    isPremium: false,
  },
  {
    id: 'worker7',
    name: 'Đặng Minh G',
    fullName: 'Đặng Minh G',
    email: 'worker7@example.com',
    role: UserRole.WORKER,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=G',
    verified: true,
    rating: 4.8,
    ratingCount: 30,
    skills: ['Premiere', 'After Effects', 'TikTok'],
    bio: 'Video Editor. Chuyên edit video ngắn viral cho TikTok, Reels.',
    title: 'Video Editor',
    isPremium: false,
  },

  // --- BUSINESSES (IDs 1-22 matching Companies list) ---
  {
    id: '1',
    name: 'VNG Corporation',
    email: 'hr@vng.com.vn',
    role: UserRole.BUSINESS,
    avatar: 'https://picsum.photos/100/100?random=c1',
    verified: true,
    rating: 4.9,
    ratingCount: 320,
    bio: 'Công nghệ & Game',
    industry: 'Công nghệ & Game',
    address: 'Z06 Đường số 13, Phường Tân Thuận Đông, Quận 7, TP. HCM',
    followersCount: 124532,
    jobsCount: 42,
    description: 'VNG là công ty công nghệ Việt Nam, thành lập năm 2004. VNG hoạt động trong 4 mảng chính: Trò chơi trực tuyến, Nền tảng kết nối, Thanh toán điện tử và Điện toán đám mây.',
    isPremium: true,
  },
  {
    id: '2',
    name: 'FPT Software',
    email: 'hr@fpt.com.vn',
    role: UserRole.BUSINESS,
    avatar: 'https://picsum.photos/100/100?random=c2',
    verified: true,
    rating: 4.7,
    ratingCount: 156,
    bio: 'Phần mềm & IT',
    industry: 'Phần mềm & IT',
    address: 'Lô T2, Đường D1, Khu công nghệ cao, Quận 9, TP. HCM',
    followersCount: 345102,
    jobsCount: 156,
    description: 'FPT Software là công ty thành viên của FPT, tập đoàn công nghệ hàng đầu Việt Nam. Chúng tôi cung cấp dịch vụ xuất khẩu phần mềm tại hơn 26 quốc gia.',
    isPremium: true
  },
  {
    id: '3',
    name: 'Tập đoàn Masan',
    email: 'hr@masan.vn',
    role: UserRole.BUSINESS,
    avatar: 'https://picsum.photos/100/100?random=c3',
    verified: true,
    rating: 4.5,
    ratingCount: 89,
    bio: 'Hàng tiêu dùng',
    industry: 'Hàng tiêu dùng',
    address: 'Nguyễn Huệ, Quận 1, TP. HCM',
    followersCount: 89400,
    jobsCount: 89,
    description: 'Masan Group là một trong những công ty lớn nhất trong khu vực kinh tế tư nhân Việt Nam, tập trung vào lĩnh vực hàng tiêu dùng và tài nguyên.',
    isPremium: true
  },
  {
    id: '4',
    name: 'Vietcombank',
    email: 'hr@vietcombank.com.vn',
    role: UserRole.BUSINESS,
    avatar: 'https://picsum.photos/100/100?random=c4',
    verified: true,
    rating: 4.8,
    ratingCount: 24,
    bio: 'Ngân hàng Thương mại Cổ phần Ngoại thương Việt Nam',
    industry: 'Ngân hàng',
    address: '198 Trần Quang Khải, Hoàn Kiếm, Hà Nội',
    followersCount: 210050,
    jobsCount: 24,
    description: 'Vietcombank là một trong những ngân hàng thương mại lớn nhất Việt Nam, dẫn đầu về hiệu quả hoạt động và chất lượng dịch vụ.',
    isPremium: true
  },
  {
    id: '5',
    name: 'VinGroup',
    email: 'hr@vingroup.vn',
    role: UserRole.BUSINESS,
    avatar: 'https://picsum.photos/100/100?random=c5',
    verified: true,
    rating: 4.6,
    ratingCount: 610,
    bio: 'Đa ngành',
    industry: 'Đa ngành',
    address: '7 Đường Bằng Lăng 1, Vinhomes Riverside, Long Biên, Hà Nội',
    followersCount: 560780,
    jobsCount: 210,
    description: 'Vingroup là tập đoàn kinh tế tư nhân đa ngành hàng đầu Việt Nam, hoạt động trong các lĩnh vực Bất động sản, Dịch vụ - Giải trí, Công nghiệp.',
    isPremium: true,
  },
  {
    id: '6',
    name: 'Shopee Vietnam',
    email: 'hr@shopee.vn',
    role: UserRole.BUSINESS,
    avatar: 'https://picsum.photos/100/100?random=c6',
    verified: true,
    rating: 4.4,
    ratingCount: 67,
    bio: 'Thương mại điện tử',
    industry: 'Thương mại điện tử',
    address: 'Saigon Centre, Quận 1, TP. HCM',
    followersCount: 412300,
    jobsCount: 67,
    description: 'Shopee là nền tảng thương mại điện tử hàng đầu tại Đông Nam Á và Đài Loan, cung cấp trải nghiệm mua sắm trực tuyến dễ dàng và an toàn.',
    isPremium: true
  },
  {
    id: '7',
    name: 'Tech Corp',
    email: 'hr@techcorp.com',
    role: UserRole.BUSINESS,
    avatar: 'https://picsum.photos/100/100?random=1',
    verified: true,
    rating: 4.5,
    ratingCount: 10,
    bio: 'Công nghệ',
    industry: 'Công nghệ',
    address: 'Quận 1, TP. HCM',
    followersCount: 34210,
    jobsCount: 8,
    description: 'Tech Corp là công ty startup công nghệ chuyên về phát triển các ứng dụng di động và giải pháp AI cho doanh nghiệp.',
    isPremium: true,
  },
  {
    id: '8',
    name: 'Retail Mart',
    email: 'hr@retailmart.vn',
    role: UserRole.BUSINESS,
    avatar: 'https://picsum.photos/100/100?random=6',
    verified: true,
    rating: 4.1,
    ratingCount: 24,
    bio: 'Bán lẻ',
    industry: 'Bán lẻ',
    address: 'Quận 3, TP. HCM',
    followersCount: 12540,
    jobsCount: 3,
    description: 'Retail Mart là chuỗi siêu thị tiện lợi phủ rộng khắp các tỉnh thành Việt Nam, cung cấp thực phẩm sạch và nhu yếu phẩm.',
    isPremium: false,
  },
  {
    id: '9',
    name: 'LogiFast',
    email: 'hr@logifast.vn',
    role: UserRole.BUSINESS,
    avatar: 'https://picsum.photos/100/100?random=7',
    verified: true,
    rating: 3.9,
    ratingCount: 18,
    bio: 'Logistics',
    industry: 'Logistics',
    address: 'Dĩ An, Bình Dương',
    followersCount: 9120,
    jobsCount: 2,
    description: 'LogiFast cung cấp các giải pháp vận chuyển kho bãi tối ưu, giúp doanh nghiệp tiết kiệm chi phí và thời gian giao nhận.',
    isPremium: false,
  },
  {
    id: '10',
    name: 'SeaFood House',
    email: 'hr@seafoodhouse.vn',
    role: UserRole.BUSINESS,
    avatar: 'https://picsum.photos/100/100?random=8',
    verified: true,
    rating: 4.4,
    ratingCount: 30,
    bio: 'F&B',
    industry: 'F&B',
    address: 'Sơn Trà, Đà Nẵng',
    followersCount: 18330,
    jobsCount: 1,
    description: 'SeaFood House tự hào mang đến thực phẩm hải sản tươi sống chất lượng nhất từ đại dương đến bàn ăn của khách hàng.',
    isPremium: false,
  },
  {
    id: '11',
    name: 'Media House',
    email: 'hr@mediahouse.vn',
    role: UserRole.BUSINESS,
    avatar: 'https://picsum.photos/100/100?random=9',
    verified: true,
    rating: 4.7,
    ratingCount: 40,
    bio: 'Truyền thông',
    industry: 'Truyền thông',
    address: 'Quận 10, TP. HCM',
    followersCount: 25600,
    jobsCount: 1,
    description: 'Media House là đơn vị truyền thông sáng tạo, chuyên tổ chức sự kiện và xây dựng chiến lược thương hiệu cho các tập đoàn lớn.',
    isPremium: false,
  },
  {
    id: '12',
    name: 'City Hospital',
    email: 'hr@cityhospital.vn',
    role: UserRole.BUSINESS,
    avatar: 'https://picsum.photos/100/100?random=10',
    verified: true,
    rating: 4.6,
    ratingCount: 39,
    bio: 'Y tế',
    industry: 'Y tế',
    address: 'Ba Đình, Hà Nội',
    followersCount: 39120,
    jobsCount: 1,
    description: 'City Hospital là bệnh viện đa khoa quốc tế, cung cấp dịch vụ khám chữa bệnh chất lượng cao với đội ngũ chuyên gia hàng đầu.',
    isPremium: false
  },
  {
    id: '13',
    name: 'Fast Delivery',
    email: 'hr@fastdelivery.vn',
    role: UserRole.BUSINESS,
    avatar: 'https://picsum.photos/100/100?random=11',
    verified: true,
    rating: 3.8,
    ratingCount: 28,
    bio: 'Giao hàng',
    industry: 'Giao hàng',
    address: 'Bình Thạnh, TP. HCM',
    followersCount: 28430,
    jobsCount: 1,
    description: 'Fast Delivery là đơn vị vận chuyển hỏa tốc, cam kết giao nhận hàng hóa trong nội thành chỉ từ 2 giờ.',
    isPremium: false
  },
  {
    id: '14',
    name: 'Finance Pro',
    email: 'hr@financepro.vn',
    role: UserRole.BUSINESS,
    avatar: 'https://picsum.photos/100/100?random=12',
    verified: true,
    rating: 4.2,
    ratingCount: 15,
    bio: 'Tài chính – Kế toán',
    industry: 'Tài chính – Kế toán',
    address: 'Hai Bà Trưng, Hà Nội',
    followersCount: 15204,
    jobsCount: 1,
    description: 'Finance Pro cung cấp giải pháp tư vấn tài chính và kế toán thuế chuyên nghiệp cho các doanh nghiệp SME.',
    isPremium: false
  },
  {
    id: '15',
    name: 'Language Center',
    email: 'hr@languagecenter.vn',
    role: UserRole.BUSINESS,
    avatar: 'https://picsum.photos/100/100?random=13',
    verified: true,
    rating: 4.8,
    ratingCount: 22,
    bio: 'Giáo dục',
    industry: 'Giáo dục',
    address: 'Cầu Giấy, Hà Nội',
    followersCount: 22540,
    jobsCount: 1,
    description: 'Language Center là trung tâm đào tạo ngoại ngữ hàng đầu, chuyên luyện thi IELTS và tiếng Anh giao tiếp.',
    isPremium: false
  },
  {
    id: '16',
    name: 'BuildTech',
    email: 'hr@buildtech.vn',
    role: UserRole.BUSINESS,
    avatar: 'https://picsum.photos/100/100?random=14',
    verified: true,
    rating: 4.0,
    ratingCount: 10,
    bio: 'Xây dựng',
    industry: 'Xây dựng',
    address: 'Quận 2, TP. HCM',
    followersCount: 9980,
    jobsCount: 1,
    description: 'BuildTech chuyên về thiết kế và thi công các công trình dân dụng, nhà phố với phong cách kiến trúc hiện đại.',
    isPremium: false
  },
  {
    id: '17',
    name: 'Support Now',
    email: 'hr@supportnow.vn',
    role: UserRole.BUSINESS,
    avatar: 'https://picsum.photos/100/100?random=15',
    verified: true,
    rating: 4.3,
    ratingCount: 18,
    bio: 'CSKH',
    industry: 'CSKH',
    address: 'Tân Bình, TP. HCM',
    followersCount: 18450,
    jobsCount: 1,
    description: 'Support Now cung cấp dịch vụ outsource chăm sóc khách hàng chuyên nghiệp qua hotline và live chat.',
    isPremium: false
  },
  {
    id: '18',
    name: 'Digital Agency',
    email: 'hr@digitalagency.vn',
    role: UserRole.BUSINESS,
    avatar: 'https://picsum.photos/100/100?random=16',
    verified: true,
    rating: 4.0,
    ratingCount: 7,
    bio: 'Marketing',
    industry: 'Marketing',
    address: 'Quận 1, TP. HCM',
    followersCount: 7390,
    jobsCount: 1,
    description: 'Digital Agency là đơn vị thực thi các chiến dịch marketing online sáng tạo, tăng trưởng doanh thu cho nhãn hàng.',
    isPremium: false
  },
  {
    id: '19',
    name: 'Ocean Hotel',
    email: 'hr@oceanhotel.vn',
    role: UserRole.BUSINESS,
    avatar: 'https://picsum.photos/100/100?random=17',
    verified: true,
    rating: 4.5,
    ratingCount: 13,
    bio: 'Du lịch – Khách sạn',
    industry: 'Du lịch – Khách sạn',
    address: 'Nha Trang, Khánh Hòa',
    followersCount: 13250,
    jobsCount: 1,
    description: 'Ocean Hotel là khách sạn nghỉ dưỡng 5 sao ven biển, mang lại trải nghiệm thư giãn tuyệt vời cho du khách.',
    isPremium: false
  },
  {
    id: '20',
    name: 'Clean Service',
    email: 'hr@cleanservice.vn',
    role: UserRole.BUSINESS,
    avatar: 'https://picsum.photos/100/100?random=18',
    verified: true,
    rating: 3.6,
    ratingCount: 5,
    bio: 'Lao động phổ thông',
    industry: 'Lao động phổ thông',
    address: 'Thanh Xuân, Hà Nội',
    followersCount: 4980,
    jobsCount: 1,
    description: 'Clean Service cung cấp dịch vụ giúp việc gia đình và vệ sinh công nghiệp uy tín hàng đầu.',
    isPremium: false
  },
  {
    id: '21',
    name: 'Creative Studio',
    email: 'hr@creativestudio.vn',
    role: UserRole.BUSINESS,
    avatar: 'https://picsum.photos/100/100?random=19',
    verified: true,
    rating: 4.9,
    ratingCount: 20,
    bio: 'Sáng tạo',
    industry: 'Sáng tạo',
    address: 'Quận 3, TP. HCM',
    followersCount: 20110,
    jobsCount: 1,
    description: 'Creative Studio là không gian làm việc của các nghệ sĩ and designer, nơi ra đời những ý tưởng đột phá.',
    isPremium: false
  },
  {
    id: '22',
    name: 'Factory One',
    email: 'hr@factoryone.vn',
    role: UserRole.BUSINESS,
    avatar: 'https://picsum.photos/100/100?random=20',
    verified: true,
    rating: 3.7,
    ratingCount: 16,
    bio: 'Sản xuất',
    industry: 'Sản xuất',
    address: 'Quận 9, TP. HCM',
    followersCount: 16740,
    jobsCount: 1,
    description: 'Factory One là nhà máy sản xuất linh kiện điện tử hiện đại, cung ứng cho các đối tác toàn cầu.',
    isPremium: false
  },

  // --- EXTRA BUSINESSES (IDs 23+) ---
  {
    id: '23',
    name: 'Công ty TNHH Tech Solutions',
    email: 'hr@techsolutions.vn',
    role: UserRole.BUSINESS,
    avatar: 'https://i.pravatar.cc/150?img=20',
    verified: true,
    rating: 4.9,
    ratingCount: 45,
    bio: 'Công ty công nghệ hàng đầu Việt Nam',
    industry: 'Công nghệ',
    address: 'Quận 7, TP. HCM',
    followersCount: 1200,
    jobsCount: 5,
    description: 'Chuyên phát triển phần mềm và giải pháp doanh nghiệp.',
    isPremium: true,
  },
  {
    id: '24',
    name: 'Công ty Cổ phần Digital Marketing VN',
    email: 'contact@digitalmarketing.vn',
    role: UserRole.BUSINESS,
    avatar: 'https://i.pravatar.cc/150?img=25',
    verified: true,
    rating: 4.7,
    ratingCount: 32,
    bio: 'Agency Marketing số 1 Việt Nam',
    industry: 'Marketing',
    address: 'Quận 1, TP. HCM',
    followersCount: 3500,
    jobsCount: 12,
    description: 'Chuyên cung cấp giải pháp marketing tổng thể cho doanh nghiệp.',
    isPremium: true,
  },
];

// Helper to get businesses from mockUsers
export const mockBusinesses: Record<string, any> = mockUsers
  .filter(u => u.role === UserRole.BUSINESS)
  .reduce((acc, u) => ({ ...acc, [u.id]: u }), {});

// --- MOCK JOBS ---
export const mockJobs: JobResponse[] = [
  {
    id: '1',
    businessId: '7',
    title: 'Software Engineer',
    requirements: 'React,Node.js,SQL',
    salary: '20-30 triệu',
    location: 'Hồ Chí Minh',
    type: JobType.FULL_TIME,
    description: 'Develop web applications',
    minRating: 4.0,
    postedAt: '2026-01-03T00:00:00Z',
    status: JobStatus.OPEN,
    businessName: 'Tech Corp',
    businessAvatar: 'https://picsum.photos/100/100?random=1',
    businessRating: 4.5,
    businessRatingCount: 10,
    verified: true
  },
  {
    id: '6',
    businessId: '8',
    title: 'Nhân viên bán hàng',
    requirements: 'Giao tiếp tốt,Chăm sóc khách hàng',
    salary: '8-12 triệu',
    location: 'Hồ Chí Minh',
    type: JobType.FULL_TIME,
    description: 'Tư vấn và bán sản phẩm tại cửa hàng',
    minRating: 3.8,
    postedAt: '2026-01-01T00:00:00Z',
    status: JobStatus.OPEN,
    businessName: 'Retail Mart',
    businessAvatar: 'https://picsum.photos/100/100?random=6',
    businessRating: 4.1,
    businessRatingCount: 24,
    verified: true
  },
  {
    id: '7',
    businessId: '9',
    title: 'Nhân viên kho',
    requirements: 'Sắp xếp hàng hóa,Sức khỏe tốt',
    salary: '7-10 triệu',
    location: 'Bình Dương',
    type: JobType.FULL_TIME,
    description: 'Quản lý và xuất nhập kho',
    minRating: 3.2,
    postedAt: '2025-12-28T00:00:00Z',
    status: JobStatus.OPEN,
    businessName: 'LogiFast',
    businessAvatar: 'https://picsum.photos/100/100?random=7',
    businessRating: 3.9,
    businessRatingCount: 18,
    verified: true
  },
  {
    id: '8',
    businessId: '10',
    title: 'Phục vụ nhà hàng',
    requirements: 'Nhanh nhẹn,Thái độ tốt',
    salary: '6-9 triệu',
    location: 'Đà Nẵng',
    type: JobType.PART_TIME,
    description: 'Phục vụ khách hàng tại nhà hàng',
    minRating: 4.1,
    postedAt: '2025-12-05T00:00:00Z',
    status: JobStatus.OPEN,
    businessName: 'SeaFood House',
    businessAvatar: 'https://picsum.photos/100/100?random=8',
    businessRating: 4.4,
    businessRatingCount: 30,
    verified: true
  },
  {
    id: '9',
    businessId: '11',
    title: 'Content Creator',
    requirements: 'Viết lách,Sáng tạo nội dung',
    salary: '12-18 triệu',
    location: 'Remote',
    type: JobType.FREELANCE,
    description: 'Viết bài marketing và social media',
    minRating: 4.6,
    postedAt: '2025-11-05T00:00:00Z',
    status: JobStatus.OPEN,
    businessName: 'Media House',
    businessAvatar: 'https://picsum.photos/100/100?random=9',
    businessRating: 4.7,
    businessRatingCount: 40
  },
  {
    id: '21',
    businessId: '1',
    title: 'Game Backend Developer',
    requirements: 'Java,Spring Boot,MySQL',
    salary: '25-40 triệu',
    location: 'Hồ Chí Minh',
    type: JobType.FULL_TIME,
    description: 'Phát triển backend cho game online',
    minRating: 4.5,
    postedAt: '2025-01-04T00:00:00Z',
    status: JobStatus.OPEN,
    businessName: 'VNG Corporation',
    businessAvatar: 'https://picsum.photos/100/100?random=c1',
    businessRating: 4.9,
    businessRatingCount: 320
  },
  {
    id: '27',
    businessId: '5',
    title: 'Data Analyst',
    requirements: 'SQL,Power BI,Python',
    salary: '22-35 triệu',
    location: 'Hà Nội',
    type: JobType.FULL_TIME,
    description: 'Phân tích dữ liệu kinh doanh tập đoàn',
    minRating: 4.2,
    postedAt: '2025-11-05T00:00:00Z',
    status: JobStatus.OPEN,
    businessName: 'VinGroup',
    businessAvatar: 'https://picsum.photos/100/100?random=c5',
    businessRating: 4.6,
    businessRatingCount: 610
  },
  {
    id: '10',
    businessId: '12',
    title: 'Điều dưỡng viên',
    requirements: 'Chứng chỉ hành nghề, Tận tâm',
    salary: '15-22 triệu',
    location: 'Hồ Chí Minh',
    type: JobType.FULL_TIME,
    description: 'Chăm sóc bệnh nhân tại bệnh viện quốc tế',
    minRating: 4.3,
    postedAt: '2025-12-01T00:00:00Z',
    status: JobStatus.OPEN,
    businessName: 'City Hospital',
    businessAvatar: 'https://picsum.photos/100/100?random=10',
    businessRating: 4.8,
    businessRatingCount: 55,
    verified: true
  },
  {
    id: '11',
    businessId: '13',
    title: 'Tài xế giao hàng',
    requirements: 'Bằng lái xe máy, Rành đường thành phố',
    salary: '10-15 triệu',
    location: 'Hà Nội',
    type: JobType.CONTRACT,
    description: 'Giao nhận bưu kiện trong khu vực nội thành',
    minRating: 3.5,
    postedAt: '2025-12-10T00:00:00Z',
    status: JobStatus.OPEN,
    businessName: 'Fast Delivery',
    businessAvatar: 'https://picsum.photos/100/100?random=11',
    businessRating: 3.8,
    businessRatingCount: 28,
    verified: true
  },
  {
    id: '12',
    businessId: '14',
    title: 'Kế toán sơ cấp',
    requirements: 'Tốt nghiệp chuyên ngành kế toán, Excel tốt',
    salary: '8-12 triệu',
    location: 'Đà Nẵng',
    type: JobType.FULL_TIME,
    description: 'Hỗ trợ công việc kế toán thuế và nội bộ',
    minRating: 4.0,
    postedAt: '2025-11-20T00:00:00Z',
    status: JobStatus.OPEN,
    businessName: 'Finance Pro',
    businessAvatar: 'https://picsum.photos/100/100?random=12',
    businessRating: 4.2,
    businessRatingCount: 15,
    verified: true
  },
  {
    id: '13',
    businessId: '15',
    title: 'Giáo viên tiếng Anh',
    requirements: 'IELTS 7.0+, Kỹ năng sư phạm tốt',
    salary: '20-35 triệu',
    location: 'Hồ Chí Minh',
    type: JobType.PART_TIME,
    description: 'Giảng dạy tiếng Anh giao tiếp cho người đi làm',
    minRating: 4.5,
    postedAt: '2025-12-15T00:00:00Z',
    status: JobStatus.OPEN,
    businessName: 'Language Center',
    businessAvatar: 'https://picsum.photos/100/100?random=13',
    businessRating: 4.8,
    businessRatingCount: 22,
    verified: true
  },
  {
    id: '14',
    businessId: '4',
    title: 'Giao dịch viên ngân hàng',
    requirements: 'Ngoại hình sáng,Khả năng giao tiếp tốt',
    salary: '12-18 triệu',
    location: 'Hà Nội',
    type: JobType.FULL_TIME,
    description: 'Thực hiện các giao dịch tại quầy cho khách hàng cá nhân',
    minRating: 4.0,
    postedAt: '2025-12-20T00:00:00Z',
    status: JobStatus.OPEN,
    businessName: 'Vietcombank',
    businessAvatar: 'https://picsum.photos/100/100?random=c4',
    businessRating: 4.8,
    businessRatingCount: 24,
    verified: true
  },
  {
    id: '15',
    businessId: '21',
    title: 'Thực tập sinh thiết kế',
    requirements: 'Biết sử dụng Figma,Photoshop cơ bản',
    salary: '2-4 triệu',
    location: 'TP. HCM',
    type: JobType.INTERNSHIP,
    description: 'Hỗ trợ thiết kế các ấn phẩm social media',
    minRating: 3.0,
    postedAt: '2026-01-05T00:00:00Z',
    status: JobStatus.OPEN,
    businessName: 'Creative Studio',
    businessAvatar: 'https://picsum.photos/100/100?random=19',
    businessRating: 4.9,
    businessRatingCount: 20,
    verified: true
  }
];

// --- MOCK WORK SESSIONS ---
export const mockWorkSessions: any[] = [
  {
    id: '1',
    jobId: 'job1',
    jobTitle: 'Software Engineer',
    businessId: '23',
    businessName: 'Công ty TNHH Tech Solutions',
    workerId: '101',
    workerName: 'Nguyễn Văn An',
    status: 'COMPLETED',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    firstRatedAt: '2026-01-01T00:00:00Z',
    businessRated: true,
    workerRated: true,
    businessRating: 4,
    businessComment: 'Good work',
    workerRating: 5,
    workerComment: 'Excellent experience',
    workerToBusinessHistory: [
      { rating: 4, comment: 'Initial comment', timestamp: '2026-01-01T10:00:00Z', type: 'initial', editCount: 0 },
      { rating: 5, comment: 'Updated comment', timestamp: '2026-01-01T12:00:00Z', type: 'edit', editCount: 1 },
      { rating: 5, comment: 'Supplemental comment', timestamp: '2026-01-01T14:00:00Z', type: 'supplement', editCount: 2 },
    ],
    businessToWorkerHistory: [
      { rating: 5, comment: 'Initial', timestamp: '2026-01-01T11:00:00Z', type: 'initial', editCount: 0 },
    ]
  },
  {
    id: '2',
    jobId: 'job2',
    jobTitle: 'Designer',
    businessId: '24',
    businessName: 'Công ty Cổ phần Digital Marketing VN',
    workerId: '102',
    workerName: 'Trần Thị Bình',
    status: 'COMPLETED',
    createdAt: '2024-01-02T00:00:00Z',
    updatedAt: '2025-12-31T00:00:00Z',
    firstRatedAt: '2025-12-31T00:00:00Z',
    businessRated: true,
    workerRated: true,
    businessRating: 3,
    businessComment: 'Average',
    workerRating: 4,
    workerComment: 'Good',
    workerToBusinessHistory: [
      { rating: 3, comment: 'Initial', timestamp: '2025-12-31T10:00:00Z', type: 'initial', editCount: 0 },
    ],
    businessToWorkerHistory: [
      { rating: 4, comment: 'Initial', timestamp: '2025-12-31T11:00:00Z', type: 'initial', editCount: 0 },
      { rating: 4, comment: 'Supplemental', timestamp: '2025-12-31T13:00:00Z', type: 'supplement', editCount: 1 },
    ]
  },
  {
    id: '3',
    jobId: 'job3',
    jobTitle: 'Project Manager',
    businessId: '23',
    businessName: 'Công ty TNHH Tech Solutions',
    workerId: '106',
    workerName: 'Phạm Quốc Duy',
    status: 'COMPLETED',
    createdAt: '2025-12-30T00:00:00Z',
    updatedAt: '2026-01-01T14:00:00Z',
    firstRatedAt: '2026-01-01T14:00:00Z',
    businessRated: true,
    workerRated: true,
    businessRating: 4.5,
    businessComment: 'Great management',
    workerRating: 4,
    workerComment: 'Challenging project',
    workerToBusinessHistory: [
      { rating: 4, comment: 'Initial review', timestamp: '2026-01-01T15:00:00Z', type: 'initial', editCount: 0 },
      { rating: 4.5, comment: 'Added details', timestamp: '2026-01-01T16:00:00Z', type: 'supplement', editCount: 1 },
    ],
    businessToWorkerHistory: [
      { rating: 4, comment: 'Good job', timestamp: '2026-01-01T14:30:00Z', type: 'initial', editCount: 0 },
    ]
  },
  {
    id: '4',
    jobId: 'job4',
    jobTitle: 'Marketing Specialist',
    businessId: '24',
    businessName: 'Công ty Cổ phần Digital Marketing VN',
    workerId: '104',
    workerName: 'Lê Minh Châu',
    status: 'ACCEPTED',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    firstRatedAt: '',
    businessRated: false,
    workerRated: false
  }
];

// --- MOCK APPLICANTS ---
export const mockApplicants: any[] = [
  {
    id: 'session1',
    jobId: '1',
    workerId: '101', // Nguyễn Văn An
    businessId: '1', // VNG
    status: 'PENDING',
    createdAt: '2025-01-02T00:00:00Z',
    jobTitle: 'Software Engineer',
    businessName: 'VNG Corporation',
    workerName: 'Nguyễn Văn An'
  },
  {
    id: 'session2',
    jobId: '1',
    workerId: '102', // Trần Thị Bình
    businessId: '1',
    status: 'ACCEPTED',
    createdAt: '2025-01-03T00:00:00Z',
    jobTitle: 'Software Engineer',
    businessName: 'VNG Corporation',
    workerName: 'Trần Thị Bình'
  },
  {
    id: 'session4',
    jobId: '6', // Nhân viên bán hàng
    workerId: '104', // Alice Johnson (using Châu for mock)
    businessId: '8', // Retail Mart
    status: 'REJECTED',
    createdAt: '2025-02-02T00:00:00Z',
    jobTitle: 'Nhân viên bán hàng',
    businessName: 'Retail Mart',
    workerName: 'Lê Minh Châu',
    comment: 'Cần người có nhiều kinh nghiệm hơn.'
  }
];

// --- MOCK FOLLOWERS ---
export const mockFollowers: any[] = [
  {
    id: '101',
    name: 'Nguyễn Văn An',
    avatar: 'https://i.pravatar.cc/150?img=12',
    bio: 'Chuyên gia thiết kế UI/UX',
    isFollowingBack: true
  },
  {
    id: '102',
    name: 'Trần Thị Bình',
    avatar: 'https://i.pravatar.cc/150?img=5',
    bio: 'Lập trình viên Fullstack',
    isFollowingBack: false
  },
  {
    id: '104',
    name: 'Lê Minh Châu',
    avatar: 'https://i.pravatar.cc/150?img=8',
    bio: 'Chuyên viên SEO & Content',
    isFollowingBack: false
  },
  {
    id: '106',
    name: 'Phạm Quốc Duy',
    avatar: 'https://i.pravatar.cc/150?img=15',
    bio: 'AI/ML Engineer',
    isFollowingBack: true
  }
];

// --- MOCK MY ADS (Worker Manager) ---
export const mockMyAds = [
  {
    id: 'wa1',
    title: 'Thiết kế Logo & Branding',
    salary: '2 - 5 triệu',
    location: 'Hồ Chí Minh',
    createdAt: '2 ngày trước',
    type: 'FREELANCE',
    status: JobStatus.OPEN,
    description: 'Tôi có 3 năm kinh nghiệm thiết kế bộ nhận diện thương hiệu cho các startup. Chuyên sử dụng Adobe Illustrator và Photoshop.',
    requirements: 'Thiết kế Logo, Branding, In ấn, UI Design'
  },
  {
    id: 'wa2',
    title: 'Gia sư Tiếng Anh online',
    salary: '200k - 500k / giờ',
    location: 'Toàn quốc',
    createdAt: '5 ngày trước',
    type: 'PART_TIME',
    status: 'OPEN',
    description: 'IELTS 8.0, kinh nghiệm giảng dạy 2 năm. Có giáo trình riêng cho từng trình độ từ cơ bản đến nâng cao.',
    requirements: 'IELTS 8.0, Giao tiếp, Luyện thi'
  }
];

// --- MOCK PROPOSALS ---
export const mockProposals = [
  {
    id: 'p1',
    jobId: 'wa1',
    bizName: 'VinGroup',
    bizAvatar: 'https://picsum.photos/100/100?random=c5',
    time: '2 giờ trước',
    message: 'Chúng tôi thấy hồ sơ thiết kế của bạn rất phù hợp với dự án khu đô thị mới. Bạn có thể gửi thêm Portfolio không?'
  },
  {
    id: 'p2',
    jobId: 'wa1',
    bizName: 'FPT Software',
    bizAvatar: 'https://picsum.photos/100/100?random=c2',
    time: '5 giờ trước',
    message: 'Chào bạn, FPT đang tìm kiếm Freelancer thiết kế UI cho ứng dụng nội bộ. Rất mong được hợp tác.'
  },
  {
    id: 'p3',
    jobId: 'wa2',
    bizName: 'Shopee Vietnam',
    bizAvatar: 'https://picsum.photos/100/100?random=c6',
    time: '1 ngày trước',
    message: 'Chúng tôi cần gia sư tiếng Anh cho đội ngũ Support. Vui lòng phản hồi nếu bạn quan tâm.'
  }
];

// --- LOCATIONS DATA ---
export const locationsData: Record<string, string[]> = {
  'Tất cả địa điểm': [],
  'Hà Nội': ['Ba Đình', 'Hoàn Kiếm', 'Tây Hồ', 'Long Biên', 'Cầu Giấy', 'Đống Đa', 'Hai Bà Trưng', 'Hoàng Mai', 'Thanh Xuân', 'Sóc Sơn', 'Đông Anh', 'Gia Lâm', 'Nam Từ Liêm', 'Thanh Trì', 'Bắc Từ Liêm', 'Mê Linh', 'Hà Đông', 'Sơn Tây', 'Ba Vì', 'Phúc Thọ', 'Đan Phượng', 'Hoài Đức', 'Quốc Oai', 'Thạch Thất', 'Chương Mỹ', 'Thanh Oai', 'Thường Tín', 'Phú Xuyên', 'Ứng Hòa', 'Mỹ Đức'],
  'Hồ Chí Minh': ['Quận 1', 'Quận 3', 'Quận 4', 'Quận 5', 'Quận 6', 'Quận 7', 'Quận 8', 'Quận 10', 'Quận 11', 'Quận 12', 'Bình Tân', 'Bình Thạnh', 'Gò Vấp', 'Phú Nhuận', 'Tân Bình', 'Tân Phú', 'Thủ Đức', 'Bình Chánh', 'Cần Giờ', 'Củ Chi', 'Hóc Môn', 'Nhà Bè'],
  'Đà Nẵng': ['Hải Châu', 'Thanh Khê', 'Sơn Trà', 'Ngũ Hành Sơn', 'Liên Chiểu', 'Cẩm Lệ', 'Hòa Vang', 'Hoàng Sa'],
  'Hải Phòng': ['Hồng Bàng', 'Lê Chân', 'Ngô Quyền', 'Kiến An', 'Hải An', 'Đồ Sơn', 'Dương Kinh', 'Thuỷ Nguyên', 'An Dương', 'An Lão', 'Tiên Lãng', 'Vĩnh Bảo', 'Kiến Thuỵ', 'Cát Hải', 'Bạch Long Vĩ'],
  'Cần Thơ': ['Ninh Kiều', 'Ô Môn', 'Bình Thuỷ', 'Cái Răng', 'Thốt Nốt', 'Vĩnh Thạnh', 'Cờ Đỏ', 'Phong Điền', 'Thới Lai'],
  'Bình Dương': ['Thủ Dầu Một', 'Bàu Bàng', 'Dầu Tiếng', 'Bến Cát', 'Phú Giáo', 'Tân Uyên', 'Dĩ An', 'Thuận Uyên', 'Bắc Tân Uyên'],
  'Đồng Nai': ['Biên Hòa', 'Long Khánh', 'Tân Phú', 'Định Quán', 'Xuân Lộc', 'Thống Nhất', 'Cẩm Mỹ', 'Long Thành', 'Nhơn Trạch', 'Vĩnh Cửu', 'Trảng Bom'],
};

// --- HELPERS ---
export const getUserById = (id: string): User | undefined => {
  return mockUsers.find(u => u.id === id);
};

export const getUserIdByName = (name: string): string | null => {
  const foundUser = mockUsers.find(u => u.name === name);
  return foundUser ? foundUser.id : null;
};

export const getWorkSessionsByUserId = (userId: string): any[] => {
  return mockWorkSessions.filter(session => session.workerId === userId || session.businessId === userId);
};

// --- MOCK SUGGESTIONS (Connection Suggestions) ---
export const mockWorkerSuggestions = [
  { id: '101', name: 'Nguyễn Văn An', role: 'Full-stack Developer', mutual: 12, avatar: 'https://i.pravatar.cc/150?img=12' },
  { id: 'worker1', name: 'Trần Văn A', role: 'Thợ điện dân dụng', mutual: 5, avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=A' },
  { id: 'worker2', name: 'Lê Thị B', role: 'Thiết kế đồ họa', mutual: 8, avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=B' },
  { id: '106', name: 'Phạm Quốc Duy', role: 'AI/ML Engineer', mutual: 23, avatar: 'https://i.pravatar.cc/150?img=15' },
  { id: 'worker3', name: 'Phạm Minh C', role: 'Gia sư Toán Lý', mutual: 2, avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=C' },
];

export const mockCompanySuggestions = [
  { id: '5', name: 'VinGroup', role: 'Đa ngành', mutual: 150, avatar: 'https://picsum.photos/100/100?random=c5' },
  { id: '2', name: 'FPT Software', role: 'Phần mềm & IT', mutual: 85, avatar: 'https://picsum.photos/100/100?random=c2' },
  { id: '6', name: 'Shopee Vietnam', role: 'Thương mại điện tử', mutual: 67, avatar: 'https://picsum.photos/100/100?random=c6' },
  { id: '3', name: 'Tập đoàn Masan', role: 'Hàng tiêu dùng', mutual: 12, avatar: 'https://picsum.photos/100/100?random=c3' },
  { id: '4', name: 'Vietcombank', role: 'Ngân hàng', mutual: 42, avatar: 'https://picsum.photos/100/100?random=c4' },
];

export const mockSuggestions = [...mockWorkerSuggestions, ...mockCompanySuggestions];
export const mockUserFollows: string[] = ['102', '5'];

// --- UI CONTENT MOCK DATA ---
export const mockHomeSlides = [
  {
    image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1600&q=80',
    title: 'Vươn Tầm Sự Nghiệp',
    subtitle: 'Khởi đầu vạn điểm đến với hồ sơ được xác thực',
    buttonText: 'ỨNG TUYỂN NGAY',
    link: '/jobs',
    color: 'from-[#004182]/90'
  },
  {
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1600&q=80',
    title: 'Kết Nối Doanh Nghiệp',
    subtitle: 'Hơn 500+ tập đoàn hàng đầu đang tìm kiếm bạn',
    buttonText: 'KHÁM PHÁ CÔNG TY',
    link: '/companies',
    color: 'from-[#4c42bd]/90'
  },
  {
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1600&q=80',
    title: 'Hồ Sơ Tin Cậy',
    subtitle: 'Minh bạch hóa lịch sử làm việc của bạn',
    buttonText: 'TẠO HỒ SƠ',
    link: '/profile',
    color: 'from-gray-900/90'
  }
];

export const mockWorkerAds = [
  {
    id: 'worker1',
    fullName: 'Trần Văn A',
    title: 'Thợ điện nước tay nghề cao',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=A',
    rating: 4.8,
    ratingCount: 15,
    skills: ['Sửa chữa điện', 'Lắp đặt ống nước', 'Bảo trì'],
    bio: 'Hơn 5 năm kinh nghiệm làm việc tại các công trình dân dụng.',
    location: 'Hà Nội',
    expectedSalary: '500k/ngày',
    verified: true
  },
  {
    id: 'worker2',
    fullName: 'Lê Thị B',
    title: 'Thiết kế đồ họa Freelance',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=B',
    rating: 4.9,
    ratingCount: 42,
    skills: ['Photoshop', 'Illustrator', 'Logo Design'],
    bio: 'Chuyên thiết kế bộ nhận diện thương hiệu cho các startup.',
    location: 'TP. HCM',
    expectedSalary: 'Thỏa thuận',
    verified: true
  },
  {
    id: 'worker3',
    fullName: 'Phạm Minh C',
    title: 'Gia sư Toán Lý lớp 10-12',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=C',
    rating: 4.5,
    ratingCount: 8,
    skills: ['Dạy kèm', 'Toán học', 'Vật lý'],
    bio: 'Sinh viên năm cuối ĐH Bách Khoa. Kinh nghiệm ôn thi điểm cao.',
    location: 'Đà Nẵng',
    expectedSalary: '200k/giờ',
    verified: false
  },
  {
    id: 'worker4',
    fullName: 'Nguyễn Thu D',
    title: 'Content Writer SEO',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=D',
    rating: 4.7,
    ratingCount: 25,
    skills: ['SEO', 'Content Marketing', 'Copywriting'],
    bio: 'Viết bài chuẩn SEO, tăng traffic tự nhiên cho website.',
    location: 'Remote',
    expectedSalary: '150k/bài',
    verified: true
  },
  {
    id: 'worker5',
    fullName: 'Hoàng Văn E',
    title: 'Lập trình viên ReactJS',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=E',
    rating: 4.6,
    ratingCount: 12,
    skills: ['ReactJS', 'TypeScript', 'Tailwind'],
    bio: '3 năm kinh nghiệm frontend, chuyên làm dashboard.',
    location: 'TP. HCM',
    expectedSalary: '20M/tháng',
    verified: true
  },
  {
    id: 'worker6',
    fullName: 'Vũ Thị F',
    title: 'Kế toán tổng hợp',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=F',
    rating: 4.4,
    ratingCount: 19,
    skills: ['Excel', 'MISA', 'Báo cáo thuế'],
    bio: 'Cẩn thận, tỉ mỉ, có chứng chỉ kế toán trưởng.',
    location: 'Hà Nội',
    expectedSalary: '12M/tháng',
    verified: false
  },
  {
    id: 'worker7',
    fullName: 'Đặng Minh G',
    title: 'Video Editor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=G',
    rating: 4.8,
    ratingCount: 30,
    skills: ['Premiere', 'After Effects', 'TikTok'],
    bio: 'Chuyên edit video ngắn viral cho TikTok, Reels.',
    location: 'Remote',
    expectedSalary: '500k/video',
    verified: true
  }
];

export const mockNotifications = [
  { id: 1, message: 'Bạn đã được nhận vào vị trí Software Engineer tại Tech Corp', timestamp: '2026-01-01T10:00:00Z', read: false },
  { id: 2, message: 'Hồ sơ của bạn bị từ chối cho vị trí Designer tại Creative Studio', timestamp: '2025-12-31T15:00:00Z', read: true },
  { id: 3, message: 'Công việc Project Manager với Global Inc đã hoàn thành', timestamp: '2026-01-01T14:00:00Z', read: false },
];

export const mockSavedJobsList: any[] = [];

export const mockIndustries = [
  'Tất cả',
  'Công nghệ',
  'Phần mềm',
  'Tài chính',
  'Ngân hàng',
  'Marketing',
  'Giáo dục',
  'Y tế',
  'Sản xuất',
  'Xây dựng',
  'Logistics',
  'F&B',
  'Du lịch',
  'Bán lẻ',
  'Truyền thông',
  'Lao động'
];

export const mockSavedJobIds = ['1', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29'];
